### ISSUE TITLE
Last Wish Shortcut

### ISSUE THREAD

**Issue by OpenTaggingSystem** [ChaosCantrip/chaosd2#5]
Hey,

I love your project and during scanning through it I stumbled over a shortcut for Last Wish. Generally I'd expect chaosd2.com/lw/qw to work for Queen's Walk. Obviously can't think of everything, that's why I file this. If you feel like this might help please consider it constructive criticism, your project is amazing.

**Comment by ChaosCantrip** [comment]
Hi! Thank you so much for the feedback! I've added that link in [this commit](https://github.com/ChaosCantrip/chaosd2/commit/bccedc153ee31ad2e0f3dbd7a3cdd2be91615789). I haven't been able to work on any of the Last Wish maps for a while as things have been super busy recently but I'm trying to get back into making these now things have calmed down so hopefully I might have some stuff up on there soon! Glad to hear you like the project, thank you so much!
